apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  annotations:
    # IRSA - this annotation is the entire mechanism that turns the Pod's
    # projected SA token into an AWS session via sts:AssumeRoleWithWebIdentity.
    eks.amazonaws.com/role-arn: {{ .Values.serviceAccount.roleArn | quote }}
