helm:
  parameters:
  - name: image.repository
    value: ghcr.io/airflowboy/sre-project/web-app
    forcestring: true
  - name: image.tag
    value: sha-8820e397e070b63c3f0cdfe7b70f5c774cd3bdb9
    forcestring: true
