helm:
  parameters:
  - name: image.repository
    value: ghcr.io/airflowboy/sre-project/web-app
    forcestring: true
  - name: image.tag
    value: sha-100d8023fdbbcb4c510d7cce4287b5de40a77e2a
    forcestring: true
