helm:
  parameters:
  - name: image.repository
    value: ghcr.io/airflowboy/sre-project/web-app
    forcestring: true
  - name: image.tag
    value: sha-ef3c7d7fbf78969393ac605a8d02bcf7e4fc0d28
    forcestring: true
